package com.study.mapper;

import com.study.entity.Department;
import com.study.entity.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    Department selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    int updateByPrimaryKey(Department record);
}