package com.study.entity;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ID
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPT_NAME
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ID
     *
     * @return the value of DEPARTMENT.ID
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ID
     *
     * @param id the value for DEPARTMENT.ID
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPT_NAME
     *
     * @return the value of DEPARTMENT.DEPT_NAME
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPT_NAME
     *
     * @param deptName the value for DEPARTMENT.DEPT_NAME
     *
     * @mbg.generated Thu Mar 29 05:48:03 EDT 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}