package com.study.entity;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.ID
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.LASTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    private String lastname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.ID
     *
     * @return the value of EMPLOYEE.ID
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.ID
     *
     * @param id the value for EMPLOYEE.ID
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.FIRSTNAME
     *
     * @return the value of EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.FIRSTNAME
     *
     * @param firstname the value for EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.LASTNAME
     *
     * @return the value of EMPLOYEE.LASTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.LASTNAME
     *
     * @param lastname the value for EMPLOYEE.LASTNAME
     *
     * @mbg.generated Thu Mar 29 05:10:07 EDT 2018
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
}